Repository StanfordBDHG/.github, pull requests merged in 2024-01, with the labels that each got.

#46 Documentation Improvements
  .github/workflows/firebase-deploy.yml
Labels: documentation

#47 Disable Password Autofill in the Testing Script
  .github/workflows/xcodebuild-or-fastlane.yml
Labels: bug, enhancement

#48 Add build configuration parameter to enable `Debug` or `Release` builds
  .github/workflows/xcodebuild-or-fastlane.yml
Labels: enhancement
