Repository StanfordBDHG/.github, pull requests merged in 2025-01, with the labels that each got.

#90 Update the Simulator for the Xcode Documentation Building
  .github/workflows/docc-github-pages.yml
Labels: bug

#92 Update to macOS 15-based Runners to Sync with Self-Hosted Runners
  .github/workflows/archive.yml
  .github/workflows/create-and-upload-coverage-report.yml
  .github/workflows/docc-github-pages.yml
  .github/workflows/periphery.yml
  .github/workflows/xcframework.yml
  .github/workflows/xcodebuild-or-fastlane.yml
Labels: enhancement

#94 Fix CodeQL Execution on GitHub Hosted Runners
  .github/workflows/xcodebuild-or-fastlane.yml
Labels: bug

#96 Move to Linkspector
  .github/workflows/markdown-link-check.yml
Labels: bug, enhancement

#95 Add reusable action for publishing NPM packages
  .github/workflows/npm-publish-package.yml
Labels: enhancement

#99 Cleanup Periphery
  .github/workflows/periphery.yml
Labels: enhancement

#100 Add localhost to ignored Linkspector URLs
  .github/workflows/markdown-link-check.yml
Labels: enhancement
